kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: hpa-rm343639
  namespace: rm343639
  selfLink: >-
    /apis/autoscaling/v2beta2/namespaces/rm343639/horizontalpodautoscalers/hpa-rm343639
  uid: a0d4a9aa-83e1-4965-853d-9a13de5a1591
  resourceVersion: '98843215'
  creationTimestamp: '2022-07-15T19:45:04Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: autoscaling/v2beta2
      time: '2022-07-15T19:45:04Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:maxReplicas': {}
          'f:metrics': {}
          'f:minReplicas': {}
          'f:scaleTargetRef':
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: autoscaling/v1
      time: '2022-07-15T19:45:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:autoscaling.alpha.kubernetes.io/conditions': {}
            'f:autoscaling.alpha.kubernetes.io/current-metrics': {}
        'f:status':
          'f:currentCPUUtilizationPercentage': {}
          'f:currentReplicas': {}
          'f:desiredReplicas': {}
spec:
  scaleTargetRef:
    kind: Deployment
    name: blog-django-py-git
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
status:
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageValue: '0'
          averageUtilization: 0
  conditions:
    - type: AbleToScale
      status: 'True'
      lastTransitionTime: '2022-07-15T19:45:19Z'
      reason: ReadyForNewScale
      message: recommended size matches current size
    - type: ScalingActive
      status: 'True'
      lastTransitionTime: '2022-07-15T19:45:19Z'
      reason: ValidMetricFound
      message: >-
        the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
    - type: ScalingLimited
      status: 'True'
      lastTransitionTime: '2022-07-15T22:24:45Z'
      reason: TooFewReplicas
      message: the desired replica count is less than the minimum replica count
