kind: Pod
apiVersion: v1
metadata:
  generateName: blog-django-py-git-75d76f9c6-
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "",
          "interface": "eth0",
          "ips": [
              "10.131.14.245"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "",
          "interface": "eth0",
          "ips": [
              "10.131.14.245"
          ],
          "default": true,
          "dns": {}
      }]
    kubernetes.io/limit-ranger: >-
      LimitRanger plugin set: cpu, memory request for container
      blog-django-py-git; cpu, memory limit for container blog-django-py-git
    openshift.io/scc: restricted
  selfLink: /api/v1/namespaces/rm343639/pods/blog-django-py-git-75d76f9c6-6g8qj
  resourceVersion: '98698362'
  name: blog-django-py-git-75d76f9c6-6g8qj
  uid: ae6c3d37-c318-41e4-a7ae-69af61864fd4
  creationTimestamp: '2022-07-15T18:22:14Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-07-15T18:22:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:deploymentconfig': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"e8f4cf37-65c0-4913-9c21-f35fbb2e25ed"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:containers':
            'k:{"name":"blog-django-py-git"}':
              'f:image': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:env':
                .: {}
                'k:{"name":"BLOG_BANNER_COLOR"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"BLOG_SITE_NAME"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:ports':
                .: {}
                'k:{"containerPort":8080,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:protocol': {}
              'f:name': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2022-07-15T18:22:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
            'f:k8s.v1.cni.cncf.io/networks-status': {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2022-07-15T18:22:18Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.131.14.245"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
  namespace: rm343639
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: blog-django-py-git-75d76f9c6
      uid: e8f4cf37-65c0-4913-9c21-f35fbb2e25ed
      controller: true
      blockOwnerDeletion: true
  labels:
    app: blog-django-py-git
    deploymentconfig: blog-django-py-git
    pod-template-hash: 75d76f9c6
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-xx569
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: ip-10-0-142-95.us-east-2.compute.internal
  securityContext:
    seLinuxOptions:
      level: 's0:c64,c4'
    fsGroup: 1004040000
  containers:
    - resources:
        limits:
          cpu: 1500m
          memory: 2Gi
        requests:
          cpu: 5m
          memory: 50Mi
      terminationMessagePath: /dev/termination-log
      name: blog-django-py-git
      env:
        - name: BLOG_SITE_NAME
          value: rm343639
        - name: BLOG_BANNER_COLOR
          value: blue
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1004040000
      ports:
        - containerPort: 8080
          protocol: TCP
      imagePullPolicy: Always
      volumeMounts:
        - name: default-token-r2wvm
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        image-registry.openshift-image-registry.svc:5000/rm343639/blog-django-py-git@sha256:8d5a9dcbd862d6627f85ceac0595d14522eeab09ad409187a133ef4672267289
  serviceAccount: default
  volumes:
    - name: default-token-r2wvm
      secret:
        secretName: default-token-r2wvm
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-07-15T18:22:14Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-07-15T18:22:18Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-07-15T18:22:18Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-07-15T18:22:14Z'
  hostIP: 10.0.142.95
  podIP: 10.131.14.245
  podIPs:
    - ip: 10.131.14.245
  startTime: '2022-07-15T18:22:14Z'
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: blog-django-py-git
      state:
        running:
          startedAt: '2022-07-15T18:22:18Z'
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/rm343639/blog-django-py-git@sha256:8d5a9dcbd862d6627f85ceac0595d14522eeab09ad409187a133ef4672267289
      image: >-
        image-registry.openshift-image-registry.svc:5000/rm343639/blog-django-py-git:latest
      lastState: {}
      containerID: 'cri-o://b4f5cbed68e5cc97af95aae710f1ebef849877b793b16d54da5c71c5f38be0b4'
  qosClass: Burstable
